# Generated by Django 4.2.21 on 2025-06-15 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "competition_list",
                    models.CharField(
                        default="Championship",
                        help_text="Comma-separated list of competitions the team has entered for this season.",
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=10, unique=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("opponent", models.CharField(max_length=100)),
                ("is_home", models.BooleanField(default=True)),
                ("competition", models.CharField(blank=True, max_length=100)),
                (
                    "round",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Quarter-Final', 'Round 3', 'Group Stage', etc.",
                        max_length=50,
                    ),
                ),
                ("attendance", models.PositiveIntegerField(blank=True, null=True)),
                ("team_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "opponent_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.season"
                    ),
                ),
            ],
        ),
    ]
