# Generated by Django 4.2.21 on 2025-06-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="slug",
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("opponent", models.CharField(max_length=100)),
                ("is_home", models.BooleanField(default=True)),
                ("team_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "opponent_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.season"
                    ),
                ),
            ],
        ),
    ]
