# Generated by Django 4.2.21 on 2025-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="country",
            field=models.CharField(max_length=50),
        ),
    ]
