# Generated by Django 4.2.21 on 2025-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_alter_team_city_alter_team_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="competition_list",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of competitions the team has entered for this season.",
                max_length=255,
            ),
        ),
    ]
