# Generated by Django 4.2.21 on 2025-06-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_season_slug_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="notes",
        ),
        migrations.AddField(
            model_name="match",
            name="attendance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="competition",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="match",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="competition_list",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of competitions the team has entered for this season.",
                max_length=255,
                null=True,
            ),
        ),
    ]
