# Generated by Django 4.2.21 on 2025-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_alter_season_competition_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="slug",
            field=models.SlugField(blank=True, max_length=10),
        ),
    ]
