# Generated by Django 4.2.21 on 2025-06-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_alter_season_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="season",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("team", "start_date", "end_date"),
                name="unique_team_season_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("team", "slug"), name="unique_team_season_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("contributor", "slug"), name="unique_contributor_team_slug"
            ),
        ),
    ]
