# Generated by Django 4.2.21 on 2025-06-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_alter_season_unique_together_team_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="round",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scorer_name", models.CharField(max_length=100)),
                (
                    "minute",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 23, 45+2, 90+4 (leave blank if unknown)",
                        max_length=6,
                    ),
                ),
                ("is_own_goal", models.BooleanField(default=False)),
                ("is_penalty", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="team.match",
                    ),
                ),
            ],
        ),
    ]
