# Generated by Django 4.2.21 on 2025-06-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0006_alter_match_round_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="scorer_name",
            new_name="scorer",
        ),
    ]
