# Generated by Django 4.2.21 on 2025-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_rename_scorer_name_goal_scorer"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="goals",
            field=models.TextField(
                blank=True,
                help_text="Enter goal scorers, one per line. Use format: '45+2 Smith'",
            ),
        ),
        migrations.DeleteModel(
            name="Goal",
        ),
    ]
