# Generated by Django 4.2.21 on 2025-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0008_match_goals_delete_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="goals",
            field=models.TextField(
                blank=True,
                help_text="Enter goals in format: 'Smith 45+2, 76, Windass 83, Bannan 90+1'. List scorer names followed by goal minutes. Separate players with commas.",
            ),
        ),
    ]
